<?php
/**
 * Biblioteca grande de preguntas frecuentes (600 en total: 20 temas × 30).
 *
 * Alimenta al asistente (chatbot) y a la página de Ayuda. Se combina con las
 * FAQs editables del administrador sin pisarlas (se fusionan por tema y se
 * deduplican por pregunta en ws_site_pages()).
 *
 * @package Workshop
 */

defined( 'ABSPATH' ) || exit;

function ws_faq_big_library() {
    return array(
        // ------------------------------------------------------------------
        array(
            'topic' => 'Cuenta y registro',
            'items' => array(
                array( 'q' => '¿Cómo creo una cuenta gratis?', 'a' => 'Pulsa Registrarse, escribe tu nombre, correo y una contraseña. No necesitas tarjeta para empezar.' ),
                array( 'q' => '¿Qué necesito para registrarme?', 'a' => 'Solo un correo electrónico válido y una contraseña. Si quieres vender, además completas los datos de tu negocio al entrar.' ),
                array( 'q' => '¿Es realmente gratis crear la cuenta?', 'a' => 'Sí, la cuenta y la prueba inicial son gratis. Pagas solo si más adelante decides contratar un plan superior.' ),
                array( 'q' => '¿Puedo registrarme como comprador sin negocio?', 'a' => 'Claro, no necesitas tener un negocio: regístrate y compra en las tiendas del marketplace como cualquier cliente.' ),
                array( 'q' => '¿Puedo tener cuenta de comprador y de negocio a la vez?', 'a' => 'Sí, la misma cuenta sirve para comprar y para vender si montas tu tienda desde el panel.' ),
                array( 'q' => '¿Cómo activo mi cuenta?', 'a' => 'Te llega un correo de confirmación con un enlace. Tócalo y tu cuenta queda activa; revisa también el spam.' ),
                array( 'q' => 'No me llegó el correo de confirmación', 'a' => 'Revisa la carpeta de spam o correo no deseado. Si no aparece, vuelve a intentarlo o escribe a contacto y te ayudamos.' ),
                array( 'q' => '¿Puedo usar un correo temporal?', 'a' => 'No lo recomendamos: necesitas el correo para confirmar la cuenta, recuperar la contraseña y recibir avisos importantes.' ),
                array( 'q' => '¿Cuántas cuentas puedo crear?', 'a' => 'Puedes tener una cuenta principal; si necesitas más, crea las que quieras con correos distintos.' ),
                array( 'q' => '¿Cómo edito mi nombre de usuario?', 'a' => 'Entra a tu panel, ve a Ajustes o Perfil y cambia tu nombre. Se guarda al momento.' ),
                array( 'q' => '¿Cómo cambio mi correo?', 'a' => 'Desde el panel en Ajustes > Perfil puedes actualizar tu correo; el nuevo quedará activo tras confirmarlo.' ),
                array( 'q' => '¿Cómo cierro mi cuenta?', 'a' => 'Si eres dueño de un negocio, contacta con soporte por la página de Contacto y te ayudamos a cerrarla y a retirar tus datos.' ),
                array( 'q' => '¿Qué pasa si cierro mi cuenta con ventas pendientes?', 'a' => 'Es mejor resolver los pedidos pendientes antes. Si ya los resolviste, cierra la cuenta sin problema.' ),
                array( 'q' => '¿Puedo cambiar de comprador a vendedor?', 'a' => 'Sí, desde tu cuenta crea tu tienda y empieza a vender; no necesitas otra cuenta.' ),
                array( 'q' => '¿El registro tarda mucho?', 'a' => 'Menos de un minuto: solo nombre, correo y contraseña.' ),
                array( 'q' => '¿Qué hago si el registro falla?', 'a' => 'Revisa que el correo sea válido y la contraseña tenga al menos 8 caracteres. Si sigue fallando, escríbenos por contacto.' ),
                array( 'q' => '¿Puedo registrarme con mi teléfono?', 'a' => 'El registro se hace con correo; el teléfono lo añades después en tu perfil o al hacer pedidos.' ),
                array( 'q' => '¿Puedo iniciar sesión con otro método?', 'a' => 'De momento se usa correo y contraseña. Si la olvidas, usa la opción de recuperación.' ),
                array( 'q' => '¿Qué datos pide el registro?', 'a' => 'Nombre, correo y contraseña. Si montas tienda, luego añades nombre del negocio, ubicación y horario.' ),
                array( 'q' => '¿Puedo tener dos negocios en una cuenta?', 'a' => 'Un plan puede incluir varias ubicaciones o tiendas dentro del mismo negocio, gestionadas desde el panel.' ),
                array( 'q' => '¿Cómo sé que mi cuenta quedó creada?', 'a' => 'Al registrarte entras directo y recibes el correo de confirmación. Si no, revisa el spam.' ),
                array( 'q' => '¿Puedo registrarme sin internet?', 'a' => 'El registro necesita conexión. Una vez creada, la app puede funcionar sin conexión para lo básico.' ),
                array( 'q' => '¿El correo es obligatorio?', 'a' => 'Sí, es tu identificación para entrar y recuperar la cuenta.' ),
                array( 'q' => '¿Puedo cambiar mi contraseña al crear la cuenta?', 'a' => 'La contraseña se define al registrarte y puedes cambiarla después desde tu perfil.' ),
                array( 'q' => '¿Qué hago si el correo ya está registrado?', 'a' => 'Usa la opción de recuperar contraseña o inicia sesión; si no es tuyo, contacta con soporte.' ),
                array( 'q' => '¿Puedo registrarme desde el móvil?', 'a' => 'Sí, el registro funciona igual desde el móvil, la tableta o el ordenador.' ),
                array( 'q' => '¿La cuenta tiene fecha de caducidad?', 'a' => 'No, tu cuenta no caduca. Solo el plan gratuito de tu negocio tiene un período de prueba.' ),
                array( 'q' => '¿Puedo borrar mi historial de compras?', 'a' => 'El historial lo ves tú y las tiendas; si necesitas borrarlo, contacta con soporte.' ),
                array( 'q' => '¿Dónde veo mis datos de cuenta?', 'a' => 'En tu panel, sección Perfil o Ajustes: nombre, correo, teléfono y contraseña.' ),
                array( 'q' => '¿Puedo registrarme en otro idioma?', 'a' => 'Por ahora el sitio está en español; pronto habrá más idiomas.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Inicio de sesión y seguridad',
            'items' => array(
                array( 'q' => '¿Cómo entro a mi cuenta?', 'a' => 'Pulsa Entrar, escribe tu correo y contraseña. Si tienes negocio, te llevamos directo al panel.' ),
                array( 'q' => 'Olvidé mi contraseña', 'a' => 'En la pantalla de entrada pulsa ¿Olvidaste tu contraseña? y te enviaremos un enlace a tu correo.' ),
                array( 'q' => 'No me llega el correo para recuperar la contraseña', 'a' => 'Revisa el spam y espera unos minutos. Si sigue sin llegar, escríbenos desde Contacto.' ),
                array( 'q' => '¿Cómo cambio mi contraseña?', 'a' => 'Entra a tu perfil y elige cambiar contraseña: te pedirá la actual y la nueva.' ),
                array( 'q' => '¿Qué tan larga debe ser mi contraseña?', 'a' => 'Te recomendamos al menos 8 caracteres con letras y números. Mientras más larga, más segura.' ),
                array( 'q' => 'Me dice que la contraseña es incorrecta', 'a' => 'Revisa mayúsculas y que no tengas Bloq Mayús activado. Si falla, usa recuperar contraseña.' ),
                array( 'q' => '¿Puedo entrar con mi teléfono?', 'a' => 'El acceso es con correo y contraseña; el teléfono se usa para pedidos y contacto.' ),
                array( 'q' => '¿Cuántos intentos fallidos permitidos?', 'a' => 'El sistema registra los intentos fallidos y puede bloquear temporalmente el acceso desde una misma dirección si sospecha un ataque.' ),
                array( 'q' => 'Me bloquearon la cuenta por muchos intentos', 'a' => 'Espera unos minutos e inténtalo de nuevo. Si persiste, usa recuperar contraseña o contacta con soporte.' ),
                array( 'q' => '¿Cómo sé si alguien entró a mi cuenta?', 'a' => 'Revisa tus notificaciones: te avisamos de intentos de acceso sospechosos. Cambia la contraseña si dudas.' ),
                array( 'q' => '¿Puedo iniciar sesión en varios dispositivos?', 'a' => 'Sí, tu cuenta funciona en varios dispositivos a la vez.' ),
                array( 'q' => '¿Cómo cierro sesión?', 'a' => 'En el panel, busca el menú de tu usuario y pulsa Salir o Cerrar sesión.' ),
                array( 'q' => '¿Es seguro comprar en el sitio?', 'a' => 'Sí: el pedido se hace directo con la tienda, con detalle por WhatsApp y sin compartir datos de pago con terceros.' ),
                array( 'q' => '¿Debo compartir mi contraseña con mi equipo?', 'a' => 'Nunca. Para tu equipo usa la función de Trabajadores y asigna roles con sus propios accesos.' ),
                array( 'q' => '¿Cómo protejo mi cuenta de negocios?', 'a' => 'Usa una contraseña única, no la compartas y revisa periódicamente quién tiene acceso en Trabajadores.' ),
                array( 'q' => '¿Qué hago si veo actividad rara en mi cuenta?', 'a' => 'Cambia tu contraseña de inmediato y revisa los trabajadores con acceso. También puedes avisarnos desde Contacto.' ),
                array( 'q' => '¿La sesión se cierra sola?', 'a' => 'Por seguridad, la sesión puede expirar tras un tiempo de inactividad; vuelve a entrar cuando la necesites.' ),
                array( 'q' => '¿Puedo guardar mi contraseña en el navegador?', 'a' => 'Puedes, pero en equipos compartidos es mejor no guardarla.' ),
                array( 'q' => '¿Qué es el aviso de intento de intrusión?', 'a' => 'Es una alerta que te llega cuando se detectan varios intentos de acceso fallidos desde la misma dirección IP.' ),
                array( 'q' => '¿Puedo cambiar el correo de mi cuenta?', 'a' => 'Sí, desde el perfil. El nuevo correo deberás confirmarlo.' ),
                array( 'q' => '¿Qué hago si perdí el acceso a mi correo?', 'a' => 'Contacta con soporte desde la página de Contacto y verifica tu identidad para recuperar el acceso.' ),
                array( 'q' => '¿Puedo entrar si no tengo internet?', 'a' => 'Necesitas conexión para entrar. Una vez dentro, la app guarda lo esencial para trabajar sin conexión.' ),
                array( 'q' => '¿Cómo agrego un segundo factor de seguridad?', 'a' => 'Por ahora la seguridad se basa en contraseña + detección de intentos raros. Pronto habrá más opciones.' ),
                array( 'q' => '¿La contraseña se ve en algún lado?', 'a' => 'No, nunca se muestra y se guarda cifrada.' ),
                array( 'q' => '¿Puedo usar la misma contraseña en el correo y aquí?', 'a' => 'No lo recomendamos: usa contraseñas distintas para cada servicio.' ),
                array( 'q' => '¿Qué pasa si cambio la contraseña de un trabajador?', 'a' => 'Ese trabajador deberá entrar con la nueva contraseña; su rol y permisos no cambian.' ),
                array( 'q' => '¿Cómo sé qué rol tengo?', 'a' => 'En tu panel verás tu perfil con tu rol: dueño, almacenero o vendedor.' ),
                array( 'q' => '¿Puedo ver quién entra a mi negocio?', 'a' => 'El dueño puede ver la actividad del equipo en el reporte de equipo o preguntándole al asistente.' ),
                array( 'q' => '¿Debo cerrar sesión en equipos compartidos?', 'a' => 'Sí, siempre cierra sesión al terminar en un equipo que no es tuyo.' ),
                array( 'q' => '¿El sitio guarda mis contraseñas?', 'a' => 'Solo de forma cifrada y protegida, nunca en texto plano.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Planes y precios',
            'items' => array(
                array( 'q' => '¿Qué planes existen?', 'a' => 'Tenemos planes para cada tamaño de negocio, desde el inicial hasta el Pro con más productos, tiendas y trabajadores.' ),
                array( 'q' => '¿Cuánto cuesta el plan más barato?', 'a' => 'Puedes empezar gratis con la prueba. Los precios de los planes se muestran en el panel > Plan.' ),
                array( 'q' => '¿Hay prueba gratis?', 'a' => 'Sí, los negocios nuevos tienen un período de prueba gratis para montar su tienda y vender.' ),
                array( 'q' => '¿Necesito tarjeta para la prueba?', 'a' => 'No, la prueba no requiere tarjeta ni ningún pago.' ),
                array( 'q' => '¿Cómo subo de plan?', 'a' => 'Entra al panel > Plan, elige el nuevo plan y sigue el pago. Se aplica al momento.' ),
                array( 'q' => '¿Puedo bajar de plan?', 'a' => 'Sí, puedes cambiar a un plan inferior desde el panel > Plan, siempre que no superes sus límites.' ),
                array( 'q' => '¿Qué pasa si supero el límite de mi plan?', 'a' => 'El sistema te avisa y no deja crear más hasta que subas de plan o liberes espacio.' ),
                array( 'q' => '¿Cuántos productos tiene cada plan?', 'a' => 'Cada plan tiene un tope de productos; lo verás en el panel > Plan junto a tu uso actual.' ),
                array( 'q' => '¿Los planes incluyen varias tiendas?', 'a' => 'Depende del plan: los superiores incluyen varias ubicaciones o tiendas.' ),
                array( 'q' => '¿Los planes incluyen trabajadores?', 'a' => 'Sí, según el plan puedes invitar más miembros del equipo con roles.' ),
                array( 'q' => '¿Cómo pago el plan?', 'a' => 'Desde el panel > Plan verás los métodos de pago disponibles para tu zona.' ),
                array( 'q' => '¿Puedo pagar en efectivo?', 'a' => 'Algunos planes se pueden gestionar con métodos locales; mira las opciones en el panel > Plan.' ),
                array( 'q' => '¿Qué pasa cuando vence mi plan?', 'a' => 'Tu negocio vuelve al plan gratuito o se limita hasta que renueves; tus datos se conservan.' ),
                array( 'q' => '¿Puedo cancelar mi plan?', 'a' => 'Sí, desde el panel > Plan o contactando con soporte. Tu tienda seguirá en el plan gratuito.' ),
                array( 'q' => '¿Me reembolsan si cancelo?', 'a' => 'Consulta los términos de tu plan; para casos especiales contacta con soporte.' ),
                array( 'q' => '¿Dónde veo mi plan actual?', 'a' => 'En el panel > Plan aparece tu plan actual, su costo y cuánto llevas usado.' ),
                array( 'q' => '¿Qué diferencia hay entre planes?', 'a' => 'La diferencia está en los límites: productos, tiendas, trabajadores y funciones como reportes avanzados.' ),
                array( 'q' => '¿Puedo probar un plan superior antes de pagar?', 'a' => 'Consulta en el panel > Plan si hay prueba del plan superior disponible.' ),
                array( 'q' => '¿El plan se renueva solo?', 'a' => 'Si configuraste pago automático, se renueva solo; si no, recibes avisos para renovar.' ),
                array( 'q' => '¿Puedo cambiar de plan en cualquier momento?', 'a' => 'Sí, cuando quieras. Los cambios de plan se aplican de inmediato.' ),
                array( 'q' => '¿Qué pasa con mis ventas si cambio de plan?', 'a' => 'Tus productos, clientes e historial de ventas se conservan al cambiar de plan.' ),
                array( 'q' => '¿El plan es por negocio o por tienda?', 'a' => 'El plan es por negocio e incluye sus ubicaciones según el nivel.' ),
                array( 'q' => '¿Puedo pagar por varios meses?', 'a' => 'Algunos planes permiten pagos por períodos; mira las opciones en el panel > Plan.' ),
                array( 'q' => '¿Qué métodos de pago hay?', 'a' => 'Depende de tu zona; en el panel > Plan verás los métodos disponibles.' ),
                array( 'q' => '¿Los precios están en CUP?', 'a' => 'Cada negocio define su moneda; los precios del plan se muestran en la moneda del sitio.' ),
                array( 'q' => '¿Puedo comprar el plan desde el móvil?', 'a' => 'Sí, el panel funciona en el móvil y puedes gestionar tu plan desde ahí.' ),
                array( 'q' => '¿Qué incluye el plan gratuito?', 'a' => 'El plan gratuito incluye lo esencial para empezar: tienda, productos y ventas con límites básicos.' ),
                array( 'q' => '¿Puedo ver el historial de pagos?', 'a' => 'En el panel > Plan se muestra tu historial de pagos y facturación.' ),
                array( 'q' => '¿Cómo contacto para un plan a medida?', 'a' => 'Escribe por la página de Contacto o WhatsApp y te asesoramos con un plan a medida.' ),
                array( 'q' => '¿Los planes tienen contrato?', 'a' => 'No hay contratos largos: pagas tu plan y puedes cambiarlo cuando quieras.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Pagos y facturación',
            'items' => array(
                array( 'q' => '¿Cómo se paga el plan?', 'a' => 'Desde el panel > Plan eliges el método disponible y completas el pago en unos clics.' ),
                array( 'q' => '¿Puedo pagar por transferencia?', 'a' => 'Según tu zona, sí. En el panel > Plan verás si la transferencia está disponible.' ),
                array( 'q' => '¿Qué pasa si falla el pago?', 'a' => 'Tu plan no cambia y puedes reintentar. Si el problema persiste, contacta con soporte.' ),
                array( 'q' => '¿Me llega un recibo?', 'a' => 'Sí, al pagar te llega la confirmación y queda registrado en tu historial de pagos.' ),
                array( 'q' => '¿Dónde veo mis recibos?', 'a' => 'En el panel > Plan, en la sección de pagos e historial.' ),
                array( 'q' => '¿Puedo pagar en efectivo?', 'a' => 'Algunos planes se pueden gestionar con métodos locales; consulta las opciones en tu panel.' ),
                array( 'q' => '¿Cuánto cuesta renovar?', 'a' => 'El costo de renovación es el precio de tu plan según el período elegido.' ),
                array( 'q' => '¿Puedo cambiar el método de pago?', 'a' => 'Sí, desde el panel > Plan puedes actualizar tu método de pago.' ),
                array( 'q' => '¿Me cobran por cada tienda?', 'a' => 'No, pagas el plan del negocio; las ubicaciones incluidas ya están cubiertas.' ),
                array( 'q' => '¿Hay comisiones por venta?', 'a' => 'No: las ventas de tu tienda se cobran directo con tus clientes, sin comisiones del sitio.' ),
                array( 'q' => '¿Qué moneda se usa para el plan?', 'a' => 'La moneda del sitio, que se muestra en el panel > Plan.' ),
                array( 'q' => '¿Puedo pagar con tarjeta?', 'a' => 'Si tu zona lo permite, sí. Las opciones están en el panel > Plan.' ),
                array( 'q' => '¿Qué hago si me cobraron dos veces?', 'a' => 'Contacta con soporte desde la página de Contacto y lo resolvemos, con tu recibo a la mano.' ),
                array( 'q' => '¿Puedo pagar por adelantado varios meses?', 'a' => 'Algunos planes permiten pagos por varios meses; revisa las opciones en tu panel.' ),
                array( 'q' => '¿El pago es seguro?', 'a' => 'Sí, los pagos se procesan con los métodos oficiales de tu zona y no almacenamos datos de tarjetas.' ),
                array( 'q' => '¿Puedo pedir factura para mi negocio?', 'a' => 'Sí, contacta con soporte con tus datos fiscales y te la emitimos.' ),
                array( 'q' => '¿Cuándo se activa mi plan tras pagar?', 'a' => 'Inmediatamente después de confirmar el pago.' ),
                array( 'q' => '¿Qué pasa si mi pago se rechaza?', 'a' => 'Tu plan actual sigue activo hasta la fecha de vencimiento; reintenta el pago cuando puedas.' ),
                array( 'q' => '¿Puedo pagar el plan desde otra persona?', 'a' => 'Puedes coordinar que otra persona pague por ti, pero el plan se asocia a tu negocio.' ),
                array( 'q' => '¿Hay descuentos por pagar antes?', 'a' => 'Consulta en el panel > Plan si hay promociones activas para tu zona.' ),
                array( 'q' => '¿Puedo ver el total a pagar antes de confirmar?', 'a' => 'Sí, siempre se muestra el total antes de confirmar el pago.' ),
                array( 'q' => '¿Qué pasa si no renuevo mi plan?', 'a' => 'Tu negocio pasa al plan gratuito o se limita, pero tus datos e historial se conservan.' ),
                array( 'q' => '¿Puedo cancelar la renovación automática?', 'a' => 'Sí, desde el panel > Plan puedes desactivar la renovación automática.' ),
                array( 'q' => '¿Me avisan antes de cobrar?', 'a' => 'Sí, recibes avisos antes de que venza tu plan para que renueves con tiempo.' ),
                array( 'q' => '¿El precio del plan puede cambiar?', 'a' => 'Los precios se actualizan en el panel > Plan; te avisamos de cualquier cambio.' ),
                array( 'q' => '¿Cómo reclamo un cobro que no reconocí?', 'a' => 'Escribe a contacto con tu recibo y te respondemos lo antes posible.' ),
                array( 'q' => '¿Puedo pagar por WhatsApp?', 'a' => 'Según tu zona, el pago se coordina por WhatsApp o por los métodos del panel > Plan.' ),
                array( 'q' => '¿Qué incluye mi pago?', 'a' => 'El acceso a las funciones de tu plan durante el período contratado.' ),
                array( 'q' => '¿Puedo transferir mi plan a otro negocio?', 'a' => 'No directamente; contacta con soporte si necesitas reorganizar tus planes.' ),
                array( 'q' => '¿Dónde me quejo si tengo un problema de pago?', 'a' => 'En la página de Contacto o por WhatsApp, con el detalle del cobro.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Marketplace y compras',
            'items' => array(
                array( 'q' => '¿Qué es el marketplace?', 'a' => 'Es el directorio donde aparecen todas las tiendas locales del sitio para comprar cerca de ti.' ),
                array( 'q' => '¿Cómo busco un producto?', 'a' => 'Usa el buscador del marketplace: escribe el nombre del producto y te mostramos las tiendas que lo venden.' ),
                array( 'q' => '¿Cómo busco una tienda?', 'a' => 'En el marketplace usa el buscador o el listado de tiendas y elige la que quieras.' ),
                array( 'q' => '¿Puedo filtrar por tienda?', 'a' => 'Sí, entra a la página de la tienda y navega su catálogo directamente.' ),
                array( 'q' => '¿Cómo veo el precio de un producto?', 'a' => 'En la tarjeta del producto se muestra el precio y su moneda; ábrelo para ver el detalle.' ),
                array( 'q' => '¿Cómo sé si hay stock?', 'a' => 'Cada producto muestra su disponibilidad: con stock, poco stock o agotado.' ),
                array( 'q' => '¿Qué hago si un producto está agotado?', 'a' => 'Puedes escribirle a la tienda por WhatsApp para saber cuándo lo repone.' ),
                array( 'q' => '¿Puedo comparar precios entre tiendas?', 'a' => 'Sí, busca el producto en el marketplace y verás las distintas tiendas que lo ofrecen.' ),
                array( 'q' => '¿Cómo veo las categorías?', 'a' => 'Las categorías se muestran en el marketplace y dentro de cada tienda para filtrar.' ),
                array( 'q' => '¿Las tiendas son locales?', 'a' => 'Sí, el sitio conecta negocios locales con sus clientes de la zona.' ),
                array( 'q' => '¿Puedo comprar sin registrarme?', 'a' => 'Para formalizar un pedido es mejor tener tu cuenta; así haces seguimiento.' ),
                array( 'q' => '¿Cómo sé que una tienda es confiable?', 'a' => 'Revisa su valoración, reseñas y su información de contacto en su página.' ),
                array( 'q' => '¿Puedo dejar reseñas?', 'a' => 'Sí, después de tu compra puedes valorar a la tienda con estrellas y comentario.' ),
                array( 'q' => '¿Cómo contacto con una tienda?', 'a' => 'En la página de la tienda está su WhatsApp y datos de contacto para escribirle directo.' ),
                array( 'q' => '¿Las tiendas tienen horario?', 'a' => 'Sí, cada tienda muestra su horario en su página para que sepas cuándo atiende.' ),
                array( 'q' => '¿Puedo ver el catálogo de una tienda sin entrar?', 'a' => 'Sí, el catálogo es público: entra a la tienda y explora sus productos.' ),
                array( 'q' => '¿Cómo encuentro tiendas cerca de mí?', 'a' => 'Usa el listado del marketplace y revisa la ubicación que cada tienda muestra.' ),
                array( 'q' => '¿Puedo guardar tiendas favoritas?', 'a' => 'Puedes anotar sus enlaces o agregarlas a tu carrito; pronto habrá favoritos.' ),
                array( 'q' => '¿Qué moneda usan las tiendas?', 'a' => 'Cada tienda define su moneda (por ejemplo CUP) y la muestra en sus precios.' ),
                array( 'q' => '¿Las ofertas se ven en el marketplace?', 'a' => 'Las promociones las publica cada tienda en su página y catálogo.' ),
                array( 'q' => '¿Cómo se ordenan las tiendas?', 'a' => 'El listado muestra las tiendas de forma destacada y por relevancia.' ),
                array( 'q' => '¿Puedo buscar por palabra clave?', 'a' => 'Sí, el buscador encuentra productos y tiendas por palabra clave.' ),
                array( 'q' => '¿Puedo ver cuántas tiendas hay?', 'a' => 'El marketplace muestra el total de tiendas disponibles.' ),
                array( 'q' => '¿Una tienda puede vender online y en local?', 'a' => 'Sí, muchas ofrecen recogida en tienda y reparto a domicilio.' ),
                array( 'q' => '¿Cómo sé a dónde entregan?', 'a' => 'La tienda indica su zona de cobertura en su página o al confirmar el pedido.' ),
                array( 'q' => '¿Puedo pedir un producto que no veo?', 'a' => 'Escríbele a la tienda por WhatsApp y pregúntale; a veces lo tienen o lo encargan.' ),
                array( 'q' => '¿Las tiendas actualizan su stock en vivo?', 'a' => 'Sí, el stock se descuenta automáticamente con cada venta.' ),
                array( 'q' => '¿Qué hago si la tienda no responde?', 'a' => 'Espera un poco y vuelve a escribir; si es urgente, contacta con soporte del sitio.' ),
                array( 'q' => '¿Puedo ver productos destacados?', 'a' => 'Sí, las tiendas pueden destacar productos en su catálogo.' ),
                array( 'q' => '¿El marketplace funciona en el móvil?', 'a' => 'Sí, está optimizado para móvil y funciona sin problemas.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Carrito y finalizar compra',
            'items' => array(
                array( 'q' => '¿Cómo agrego un producto al carrito?', 'a' => 'En la página del producto pulsa Añadir al carrito y elige la cantidad.' ),
                array( 'q' => '¿Dónde está mi carrito?', 'a' => 'En el botón flotante del carrito, abajo en la pantalla de la tienda.' ),
                array( 'q' => '¿Puedo quitar un producto del carrito?', 'a' => 'Sí, dentro del carrito puedes eliminar o cambiar cantidades.' ),
                array( 'q' => '¿Puedo comprar en varias tiendas a la vez?', 'a' => 'El carrito funciona por tienda; cada pedido se envía a la tienda correspondiente.' ),
                array( 'q' => '¿Cómo finalizo mi compra?', 'a' => 'Abre el carrito y pulsa Finalizar: escribe tus datos y confirma el pedido.' ),
                array( 'q' => '¿Qué datos piden al finalizar?', 'a' => 'Nombre, teléfono y dirección si aplica, para que la tienda te contacte.' ),
                array( 'q' => '¿Puedo cambiar la cantidad después?', 'a' => 'Sí, edita la cantidad en el carrito antes de confirmar.' ),
                array( 'q' => '¿El carrito se guarda si salgo?', 'a' => 'Si cierras la página, el carrito puede quedar guardado en tu navegador para la próxima visita.' ),
                array( 'q' => '¿Puedo agregar notas al pedido?', 'a' => 'Según la tienda, puedes dejar notas al confirmar; si no, escríbele por WhatsApp.' ),
                array( 'q' => '¿Qué pasa si no hay stock al finalizar?', 'a' => 'La tienda verá tu pedido y coordinará contigo; si el producto se agotó, te lo indica.' ),
                array( 'q' => '¿Puedo pagar dentro del carrito?', 'a' => 'El pago se coordina con la tienda al confirmar el pedido; el carrito no cobra en línea.' ),
                array( 'q' => '¿Cuánto cuesta el envío?', 'a' => 'El costo de envío lo indica cada tienda; se suma al total cuando la tienda lo confirma.' ),
                array( 'q' => '¿Puedo ver el total antes de enviar?', 'a' => 'Sí, el carrito muestra el total de tus productos antes de confirmar.' ),
                array( 'q' => '¿Puedo elegir recogida en tienda?', 'a' => 'Sí, muchos negocios ofrecen recogida: coordínala al confirmar o por WhatsApp.' ),
                array( 'q' => '¿Qué hago si el carrito no responde?', 'a' => 'Refresca la página y revisa tu conexión. Si sigue fallando, escríbenos.' ),
                array( 'q' => '¿Puedo compartir mi carrito?', 'a' => 'No por ahora; puedes compartir el enlace del producto o de la tienda.' ),
                array( 'q' => '¿Cómo agrego más cantidad de un producto?', 'a' => 'Usa los botones de más/menos dentro del carrito o al agregarlo.' ),
                array( 'q' => '¿Puedo ver el detalle del pedido antes de enviarlo?', 'a' => 'Sí, al finalizar verás el resumen con productos y total.' ),
                array( 'q' => '¿El pedido se envía por WhatsApp?', 'a' => 'La tienda recibe tu pedido y te contacta por WhatsApp con el detalle.' ),
                array( 'q' => '¿Puedo cancelar el carrito?', 'a' => 'Solo vacíalo o ignóralo; no genera ningún compromiso hasta confirmar.' ),
                array( 'q' => '¿Qué significa pendiente?', 'a' => 'Que la tienda aún no ha confirmado tu pedido; te avisará cuando lo haga.' ),
                array( 'q' => '¿Puedo pedir sin cuenta?', 'a' => 'Recomendamos entrar con tu cuenta para hacer seguimiento del pedido.' ),
                array( 'q' => '¿Puedo cambiar el teléfono del pedido?', 'a' => 'Al confirmar escribe el teléfono correcto; si ya lo enviaste, avisa a la tienda.' ),
                array( 'q' => '¿Se pueden aplicar cupones?', 'a' => 'Si la tienda ofrece promociones, te lo indica en su catálogo o al confirmar.' ),
                array( 'q' => '¿Puedo hacer dos pedidos a la vez?', 'a' => 'Sí, cada confirmación genera un pedido independiente.' ),
                array( 'q' => '¿El carrito suma el descuento?', 'a' => 'Sí, el total refleja los precios actualizados de la tienda.' ),
                array( 'q' => '¿Qué hago si no encuentro el botón de finalizar?', 'a' => 'Asegúrate de tener productos en el carrito y de que el carrito esté abierto.' ),
                array( 'q' => '¿Puedo guardar el pedido para después?', 'a' => 'Sí, deja el carrito lleno y vuelve cuando quieras si no cierras la pestaña.' ),
                array( 'q' => '¿Cómo sé que mi pedido se envió?', 'a' => 'Verás la confirmación en pantalla y la tienda te escribirá por WhatsApp.' ),
                array( 'q' => '¿Puedo ver mis pedidos anteriores?', 'a' => 'Sí, desde tu cuenta en el historial de pedidos.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Pedidos y seguimiento',
            'items' => array(
                array( 'q' => '¿Cómo hago un pedido?', 'a' => 'Agrega productos al carrito de una tienda, finaliza con tus datos y confirma. La tienda te contacta por WhatsApp.' ),
                array( 'q' => '¿Cómo veo el estado de mi pedido?', 'a' => 'Desde tu cuenta, en el historial de pedidos verás el estado: pendiente, aceptado, completado o cancelado.' ),
                array( 'q' => '¿Qué significa pendiente?', 'a' => 'Que la tienda todavía no lo confirmó. Normalmente responde en poco tiempo.' ),
                array( 'q' => '¿Qué significa aceptado?', 'a' => 'Que la tienda confirmó tu pedido y está preparándolo.' ),
                array( 'q' => '¿Qué significa completado?', 'a' => 'Que la entrega o recogida ya se realizó.' ),
                array( 'q' => '¿Qué significa cancelado?', 'a' => 'Que el pedido no se realizó, ya sea por ti o por la tienda.' ),
                array( 'q' => '¿Puedo cancelar mi pedido?', 'a' => 'Contacta con la tienda por WhatsApp antes de que lo prepare; ella puede cancelarlo.' ),
                array( 'q' => '¿Cómo busco mi pedido?', 'a' => 'En tu historial de pedidos o con el número de pedido que recibiste.' ),
                array( 'q' => '¿Qué es el número de pedido?', 'a' => 'Es el identificador que recibes al confirmar; con él la tienda te ubica rápido.' ),
                array( 'q' => '¿Me llega confirmación del pedido?', 'a' => 'Sí, la tienda te escribe por WhatsApp y el pedido aparece en tu historial.' ),
                array( 'q' => '¿La tienda tarda en confirmar?', 'a' => 'Depende de cada negocio y su horario; si tarda, escríbele por WhatsApp.' ),
                array( 'q' => '¿Puedo modificar un pedido ya enviado?', 'a' => 'Si la tienda aún no lo prepara, coordina los cambios por WhatsApp.' ),
                array( 'q' => '¿Puedo pedir a varias tiendas?', 'a' => 'Sí, cada tienda recibe su propio pedido por separado.' ),
                array( 'q' => '¿El pedido descuenta el stock?', 'a' => 'Sí, cuando la tienda acepta el pedido el stock se descuenta automáticamente.' ),
                array( 'q' => '¿Puedo ver el total de mi pedido?', 'a' => 'Sí, el total aparece al confirmar y en tu historial.' ),
                array( 'q' => '¿Cómo contacto con la tienda por mi pedido?', 'a' => 'Usa el WhatsApp que aparece en la página de la tienda o en el detalle del pedido.' ),
                array( 'q' => '¿Qué hago si no me llega el pedido?', 'a' => 'Verifica el estado en tu historial y escribe a la tienda por WhatsApp para coordinar.' ),
                array( 'q' => '¿Puedo pedir y pagar al recibir?', 'a' => 'Sí, la mayoría de las tiendas cobran al recibir o al recoger.' ),
                array( 'q' => '¿Hay pedidos mínimos?', 'a' => 'Cada tienda define sus condiciones; consúltala en su página o por WhatsApp.' ),
                array( 'q' => '¿Puedo hacer seguimiento en vivo?', 'a' => 'El seguimiento es por WhatsApp con la tienda; el estado del pedido se actualiza en tu historial.' ),
                array( 'q' => '¿Qué hago si la tienda no acepta mi pedido?', 'a' => 'Escríbele por WhatsApp; a veces el producto se agotó o hay que coordinar el envío.' ),
                array( 'q' => '¿Puedo repetir un pedido anterior?', 'a' => 'Revisa tu historial y vuelve a agregar los mismos productos al carrito.' ),
                array( 'q' => '¿Los pedidos se guardan para siempre?', 'a' => 'Sí, tu historial de pedidos se conserva en tu cuenta.' ),
                array( 'q' => '¿Puedo ver los pedidos de otra persona?', 'a' => 'No, cada usuario ve solo sus propios pedidos.' ),
                array( 'q' => '¿Cómo sé que la tienda recibió mi pedido?', 'a' => 'Cuando el estado cambia a aceptado o la tienda te escribe por WhatsApp.' ),
                array( 'q' => '¿Puedo pagar el envío aparte?', 'a' => 'El envío se coordina con la tienda; puedes pagarlo junto al pedido o por separado.' ),
                array( 'q' => '¿Qué pasa si me equivoqué en la dirección?', 'a' => 'Avisa a la tienda por WhatsApp lo antes posible para corregirla.' ),
                array( 'q' => '¿Puedo pedir para otra persona?', 'a' => 'Sí, al finalizar escribe el nombre y teléfono de quien recibirá.' ),
                array( 'q' => '¿Cuándo llega mi pedido?', 'a' => 'La tienda te confirma el horario de entrega o recogida por WhatsApp.' ),
                array( 'q' => '¿Puedo agrupar varios pedidos en uno?', 'a' => 'Si son de la misma tienda, agrega todo al mismo carrito antes de confirmar.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Envíos y entrega',
            'items' => array(
                array( 'q' => '¿Hay envío a domicilio?', 'a' => 'Depende de cada tienda: en su página verás si ofrece reparto y su zona de cobertura.' ),
                array( 'q' => '¿Cuánto cuesta el envío?', 'a' => 'El costo lo define cada tienda según la distancia; te lo confirma al aceptar el pedido.' ),
                array( 'q' => '¿Entregan el mismo día?', 'a' => 'Algunas tiendas entregan el mismo día; consúltalo con la tienda al confirmar.' ),
                array( 'q' => '¿A qué zonas entregan?', 'a' => 'Cada tienda indica su zona de cobertura en su página o al coordinar el pedido.' ),
                array( 'q' => '¿Puedo recoger en la tienda?', 'a' => 'Sí, la mayoría ofrece recogida: coordina el horario por WhatsApp.' ),
                array( 'q' => '¿Cuánto tarda la entrega?', 'a' => 'Depende de la tienda y la zona; te lo confirman al aceptar el pedido.' ),
                array( 'q' => '¿El envío es gratis?', 'a' => 'Algunas tiendas ofrecen envío gratis sobre cierto monto; consúltalo con la tienda.' ),
                array( 'q' => '¿Puedo elegir horario de entrega?', 'a' => 'Coordina el horario directamente con la tienda por WhatsApp.' ),
                array( 'q' => '¿Qué pasa si no estoy cuando llegan?', 'a' => 'La tienda se coordina contigo; avisa si vas a estar fuera y deja un contacto.' ),
                array( 'q' => '¿Puedo pedir entrega express?', 'a' => 'Si la tienda ofrece servicio express, lo verás al coordinar el pedido.' ),
                array( 'q' => '¿El repartidor es de la tienda?', 'a' => 'Cada tienda gestiona su propia entrega; por eso el contacto es directo con ella.' ),
                array( 'q' => '¿Puedo seguir a mi repartidor?', 'a' => 'No por ahora; el seguimiento se hace por WhatsApp con la tienda.' ),
                array( 'q' => '¿Qué hago si el envío se demora?', 'a' => 'Escribe a la tienda por WhatsApp con tu número de pedido para saber el estado.' ),
                array( 'q' => '¿Puedo cambiar la dirección de entrega?', 'a' => 'Avisa a la tienda lo antes posible si el pedido no ha salido.' ),
                array( 'q' => '¿Puedo pedir a otra zona?', 'a' => 'Depende de la cobertura de la tienda; pregúntale directamente.' ),
                array( 'q' => '¿Cómo pago el envío?', 'a' => 'Se coordina con la tienda: al recibir, al recoger o junto al pedido.' ),
                array( 'q' => '¿Qué pasa si el producto llega dañado?', 'a' => 'Comunícalo a la tienda de inmediato con fotos para acordar la solución.' ),
                array( 'q' => '¿Puedo dejar instrucciones al repartidor?', 'a' => 'Sí, escribe las notas al confirmar o coordina por WhatsApp.' ),
                array( 'q' => '¿Las tiendas entregan los fines de semana?', 'a' => 'Depende del horario de cada tienda; revísalo en su página.' ),
                array( 'q' => '¿El envío incluye refrigeración?', 'a' => 'Algunas tiendas manejan productos que requieren cuidado; consúltalo con la tienda.' ),
                array( 'q' => '¿Puedo recoger sin pedido previo?', 'a' => 'Para garantizar disponibilidad, haz tu pedido primero y coordina la recogida.' ),
                array( 'q' => '¿Cuál es el punto de recogida?', 'a' => 'La tienda te indica su dirección o punto de entrega al coordinar.' ),
                array( 'q' => '¿Puedo coordinar la entrega por WhatsApp?', 'a' => 'Sí, es la vía más rápida para coordinar horarios y direcciones.' ),
                array( 'q' => '¿Qué hago si el repartidor no me encuentra?', 'a' => 'Mantén tu teléfono a mano; la tienda te llamará para ubicarte.' ),
                array( 'q' => '¿El envío es a toda la ciudad?', 'a' => 'Cada tienda define su zona; consúltala antes de confirmar.' ),
                array( 'q' => '¿Puedo pedir entrega a un tercero?', 'a' => 'Sí, indica la dirección y un teléfono de contacto de quien recibe.' ),
                array( 'q' => '¿Cuánto se demora en salir el pedido?', 'a' => 'Depende de la tienda; te avisan cuando sale.' ),
                array( 'q' => '¿Puedo cancelar el envío?', 'a' => 'Antes de que salga, coordina la cancelación con la tienda.' ),
                array( 'q' => '¿El costo de envío varía?', 'a' => 'Puede variar por distancia o peso; la tienda te lo confirma.' ),
                array( 'q' => '¿Puedo pagar el envío en efectivo?', 'a' => 'Sí, la mayoría cobra al recibir, incluyendo el costo de envío.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Devoluciones y cambios',
            'items' => array(
                array( 'q' => '¿Puedo devolver un producto?', 'a' => 'Consulta con la tienda donde compraste; cada negocio gestiona sus devoluciones.' ),
                array( 'q' => '¿Cuánto tengo para devolver?', 'a' => 'Depende de la política de cada tienda; pregúntale al momento de comprar.' ),
                array( 'q' => '¿En qué estado debe estar el producto?', 'a' => 'Normalmente sin usar y con su empaque; confirma con la tienda.' ),
                array( 'q' => '¿Cómo inicio una devolución?', 'a' => 'Escribe a la tienda por WhatsApp con tu número de pedido y el motivo.' ),
                array( 'q' => '¿Puedo cambiar un producto por otro?', 'a' => 'Si la tienda acepta cambios, coordínalo directamente con ella.' ),
                array( 'q' => '¿Me devuelven el dinero?', 'a' => 'Depende de la política de la tienda; acuerden la forma de devolución.' ),
                array( 'q' => '¿Qué hago si me llegó otro producto?', 'a' => 'Avísale a la tienda de inmediato con fotos para resolverlo.' ),
                array( 'q' => '¿Qué hago si el producto viene defectuoso?', 'a' => 'Comunícalo a la tienda con fotos y tu número de pedido; te indicará cómo proceder.' ),
                array( 'q' => '¿Quién paga el envío de la devolución?', 'a' => 'Se acuerda con la tienda; si fue error de ellos, normalmente lo asumen.' ),
                array( 'q' => '¿Puedo devolver sin el recibo?', 'a' => 'Con tu número de pedido o el WhatsApp del pedido, la tienda te ubica.' ),
                array( 'q' => '¿Las devoluciones son gratis?', 'a' => 'Depende de la política de cada tienda; consúltalo antes.' ),
                array( 'q' => '¿Puedo devolver comida?', 'a' => 'Los productos perecederos normalmente no se devuelven; confirma con la tienda.' ),
                array( 'q' => '¿Cuánto tarda el reembolso?', 'a' => 'Depende de la tienda y el método; te lo indican al aceptar la devolución.' ),
                array( 'q' => '¿Puedo devolver en la tienda física?', 'a' => 'Sí, si la tienda tiene local, coordina la entrega directa.' ),
                array( 'q' => '¿Qué pasa si ya usé el producto?', 'a' => 'Si ya se usó, normalmente no aplica devolución; acuerda con la tienda.' ),
                array( 'q' => '¿Puedo cambiar la talla?', 'a' => 'Consulta con la tienda; muchos negocios facilitan cambios de talla.' ),
                array( 'q' => '¿La garantía aplica?', 'a' => 'Algunos productos tienen garantía; pregúntale a la tienda al comprar.' ),
                array( 'q' => '¿Qué hago si no me responden la devolución?', 'a' => 'Insiste por WhatsApp y, si no hay respuesta, contacta con soporte del sitio.' ),
                array( 'q' => '¿Puedo devolver si cambié de opinión?', 'a' => 'Algunas tiendas lo aceptan dentro de un plazo; consúltalo con ella.' ),
                array( 'q' => '¿Cómo devuelvo el efectivo?', 'a' => 'Se acuerda con la tienda: en efectivo, transferencia u otro método.' ),
                array( 'q' => '¿Puedo devolver parcialmente?', 'a' => 'Si solo un producto del pedido tiene problema, coordina con la tienda la devolución parcial.' ),
                array( 'q' => '¿Me cambian el producto por otro igual?', 'a' => 'Si está disponible, la tienda puede reponerlo; coordínalo con ella.' ),
                array( 'q' => '¿Qué documentos necesito para devolver?', 'a' => 'Tu número de pedido o el WhatsApp de la compra suele ser suficiente.' ),
                array( 'q' => '¿Puedo devolver después de 30 días?', 'a' => 'Depende de la política de cada tienda; pregunta directamente.' ),
                array( 'q' => '¿Las promociones se pueden devolver?', 'a' => 'Algunas ofertas no admiten devolución; verifica las condiciones al comprar.' ),
                array( 'q' => '¿Qué hago si me cobraron de más?', 'a' => 'Avisa a la tienda con tu recibo; te aclaran o reembolsan la diferencia.' ),
                array( 'q' => '¿Puedo devolver un regalo?', 'a' => 'La tienda lo gestiona con quien hizo el pedido original.' ),
                array( 'q' => '¿Cómo sé si la tienda acepta devoluciones?', 'a' => 'Pregúntale antes de comprar o revisa su política en su página.' ),
                array( 'q' => '¿Qué hago si el paquete viene abierto?', 'a' => 'Revisa el contenido y avisa a la tienda de inmediato con fotos.' ),
                array( 'q' => '¿Puedo devolver por transferencia?', 'a' => 'Si pagaste por transferencia, la tienda puede devolverte por el mismo método.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Productos y catálogo',
            'items' => array(
                array( 'q' => '¿Cómo creo un producto?', 'a' => 'En el panel ve a Productos, pulsa Nuevo producto, llena nombre, precio y stock, y guarda.' ),
                array( 'q' => '¿Cómo edito un producto?', 'a' => 'En la lista de productos pulsa el lápiz del producto y cambia lo que necesites.' ),
                array( 'q' => '¿Cómo elimino un producto?', 'a' => 'En la lista pulsa eliminar y confirma; se quita de tu catálogo y su stock.' ),
                array( 'q' => '¿Puedo crear varios productos a la vez?', 'a' => 'Sí: en el chat puedes pedirle al asistente crear varios separados por comas, o usar la importación del panel.' ),
                array( 'q' => '¿Cómo agrego foto a un producto?', 'a' => 'Al crear o editar el producto, sube la imagen desde tu dispositivo o por URL.' ),
                array( 'q' => '¿Qué es el stock mínimo?', 'a' => 'Es la cantidad que te avisa cuando el producto está por agotarse.' ),
                array( 'q' => '¿Cómo pongo el precio?', 'a' => 'En el producto escribe el precio de venta en la moneda de tu tienda.' ),
                array( 'q' => '¿Puedo cambiar el precio?', 'a' => 'Sí, en cualquier momento desde la edición del producto.' ),
                array( 'q' => '¿Qué es la categoría del producto?', 'a' => 'Es el grupo donde lo ordenas (alimentos, limpieza, ropa…) para que se encuentre fácil.' ),
                array( 'q' => '¿Cómo agrego una categoría?', 'a' => 'Desde el panel de productos puedes crear y asignar categorías.' ),
                array( 'q' => '¿Qué es el SKU?', 'a' => 'Es el código interno del producto para identificarlo rápido en ventas y búsquedas.' ),
                array( 'q' => '¿Puedo vender por fracciones?', 'a' => 'Sí, crea un producto madre y sus fracciones; al venderlas el stock del padre se descuenta solo.' ),
                array( 'q' => '¿Qué es un producto madre?', 'a' => 'Es el producto completo del que salen las fracciones (por ejemplo 1 unidad = 2 medios).' ),
                array( 'q' => '¿Cómo se ven mis productos en el marketplace?', 'a' => 'Con su foto, precio y stock, dentro de la página de tu tienda.' ),
                array( 'q' => '¿Puedo ocultar un producto sin borrarlo?', 'a' => 'Sí, cambia su estado a inactivo y dejará de verse en tu tienda.' ),
                array( 'q' => '¿Puedo duplicar un producto?', 'a' => 'Crea uno nuevo copiando los datos del existente; no hay duplicado automático aún.' ),
                array( 'q' => '¿Cómo importo muchos productos?', 'a' => 'Usa la importación del panel con un archivo con tus productos y se cargan en lote.' ),
                array( 'q' => '¿Cómo exporto mi catálogo?', 'a' => 'Desde el panel de productos puedes exportar tu catálogo para respaldo.' ),
                array( 'q' => '¿Qué pasa si dos productos se llaman igual?', 'a' => 'Puedes diferenciarlos por SKU o categoría para no confundirlos.' ),
                array( 'q' => '¿Puedo destacar un producto?', 'a' => 'Sí, marca un producto como destacado y aparecerá primero en tu tienda.' ),
                array( 'q' => '¿Cómo ordeno mi catálogo?', 'a' => 'Por categorías y productos destacados; el orden mejora la compra.' ),
                array( 'q' => '¿Puedo poner descripción a un producto?', 'a' => 'Sí, escribe una descripción breve para que el cliente sepa qué compra.' ),
                array( 'q' => '¿Cómo actualizo el stock de un producto?', 'a' => 'Con una entrada o salida desde el módulo de Stock, o al vender se descuenta solo.' ),
                array( 'q' => '¿Puedo cambiar la foto de un producto?', 'a' => 'Sí, en la edición del producto reemplaza la imagen.' ),
                array( 'q' => '¿Los productos se ven al instante?', 'a' => 'Sí, al guardar un producto activo aparece en tu tienda al momento.' ),
                array( 'q' => '¿Puedo asignar precios por tienda?', 'a' => 'Según tu configuración, puedes manejar precios por ubicación.' ),
                array( 'q' => '¿Qué hago si no veo mi producto en el marketplace?', 'a' => 'Revisa que esté activo y con stock; también revisa tu conexión y refresca.' ),
                array( 'q' => '¿Puedo vender productos sin stock?', 'a' => 'No se recomienda; el sistema te avisa cuando el stock está bajo o agotado.' ),
                array( 'q' => '¿Cómo sé cuántos productos tengo?', 'a' => 'El panel de productos muestra el total y tu uso respecto al plan.' ),
                array( 'q' => '¿Puedo recuperar un producto eliminado?', 'a' => 'Si se eliminó, hay que crearlo de nuevo; revisa tus respaldos o exporta el catálogo.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Stock e inventario',
            'items' => array(
                array( 'q' => '¿Cómo hago una entrada de stock?', 'a' => 'En Stock pulsa Nueva entrada, elige el producto, la cantidad y la tienda, y guarda.' ),
                array( 'q' => '¿Cómo hago una salida de stock?', 'a' => 'En Stock elige la opción de salida, el producto y la cantidad; queda registrada.' ),
                array( 'q' => '¿Cómo transfiero stock entre tiendas?', 'a' => 'En Stock usa la transferencia: sale de una ubicación y entra en otra al instante.' ),
                array( 'q' => '¿Qué es el stock mínimo?', 'a' => 'Es el nivel que dispara el aviso de stock bajo para que repongas a tiempo.' ),
                array( 'q' => '¿Cómo sé qué productos están bajos?', 'a' => 'En el panel de stock verás los marcados como bajos, y el asistente te da el reporte.' ),
                array( 'q' => '¿Qué pasa si vendo más de lo que tengo?', 'a' => 'El sistema avisa y evita vender sin stock; verifica antes de confirmar la venta.' ),
                array( 'q' => '¿Puedo ajustar el stock manualmente?', 'a' => 'Sí, con entradas o salidas manuales corriges el inventario.' ),
                array( 'q' => '¿Se descuenta el stock al vender?', 'a' => 'Sí, cada venta del POS o pedido aceptado descuenta el stock automáticamente.' ),
                array( 'q' => '¿Se repone el stock al cancelar una venta?', 'a' => 'Sí, al anular una venta o rechazar un pedido el stock vuelve a su lugar.' ),
                array( 'q' => '¿Cómo veo el historial de movimientos?', 'a' => 'En el módulo de stock verás entradas, salidas y transferencias con su fecha.' ),
                array( 'q' => '¿Puedo ver el stock por tienda?', 'a' => 'Sí, cada ubicación tiene su propio stock y lo ves en el panel de stock.' ),
                array( 'q' => '¿Qué hago si el stock no cuadra?', 'a' => 'Revisa los movimientos recientes y haz un ajuste manual si encuentras la diferencia.' ),
                array( 'q' => '¿Puedo importar el stock?', 'a' => 'Puedes cargar productos con stock inicial al importar o con entradas.' ),
                array( 'q' => '¿Qué es un inventario físico?', 'a' => 'Es el conteo real; puedes ajustar el sistema para que coincida con lo que tienes.' ),
                array( 'q' => '¿Cómo agrego stock a un producto nuevo?', 'a' => 'Al crearlo pones el stock inicial, o haces una entrada después.' ),
                array( 'q' => '¿Puedo manejar fracciones en el stock?', 'a' => 'Sí, el stock de fracciones se controla y se descuenta del producto madre.' ),
                array( 'q' => '¿Me avisa cuando el stock está bajo?', 'a' => 'Sí, recibes notificaciones y el asistente te lo reporta.' ),
                array( 'q' => '¿Puedo ver el costo del inventario?', 'a' => 'Según tu configuración, los reportes pueden mostrar valores de inventario.' ),
                array( 'q' => '¿Cómo muevo mercancía de una tienda a otra?', 'a' => 'Con la transferencia del módulo de stock.' ),
                array( 'q' => '¿Puedo registrar mermas?', 'a' => 'Usa una salida de stock con el motivo para registrar pérdidas o mermas.' ),
                array( 'q' => '¿Qué pasa si elimino un producto con stock?', 'a' => 'Su stock se elimina con él; asegúrate de haberlo vendido o transferido antes.' ),
                array( 'q' => '¿Puedo ver el stock desde el móvil?', 'a' => 'Sí, el panel de stock funciona en el móvil.' ),
                array( 'q' => '¿El stock se actualiza en tiempo real?', 'a' => 'Sí, las ventas y movimientos se reflejan al instante.' ),
                array( 'q' => '¿Cómo sé cuánto reponer?', 'a' => 'Usa el stock mínimo y el historial de ventas para calcular tu reposición.' ),
                array( 'q' => '¿Puedo programar una reposición?', 'a' => 'El asistente puede recordarte con reportes; también puedes definir alertas de stock bajo.' ),
                array( 'q' => '¿Qué es stock agotado?', 'a' => 'Es cuando la cantidad llega a cero y el producto deja de venderse.' ),
                array( 'q' => '¿Puedo vender con stock cero?', 'a' => 'El sistema lo evita por defecto para no generar problemas de inventario.' ),
                array( 'q' => '¿Cómo corrijo un movimiento equivocado?', 'a' => 'Haz el movimiento inverso (entrada por salida) o ajusta manualmente.' ),
                array( 'q' => '¿Las transferencias quedan registradas?', 'a' => 'Sí, quedan en el historial con origen, destino y cantidad.' ),
                array( 'q' => '¿Puedo ver el stock de todas mis tiendas juntas?', 'a' => 'Sí, el panel muestra el stock por ubicación y el total.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Ventas y punto de venta',
            'items' => array(
                array( 'q' => '¿Cómo abro el punto de venta?', 'a' => 'En el panel ve al módulo Vender (POS) y abre la caja con el efectivo inicial.' ),
                array( 'q' => '¿Cómo registro una venta?', 'a' => 'Con la caja abierta, busca el producto, indica la cantidad, cobra y confirma.' ),
                array( 'q' => '¿Puedo vender sin caja abierta?', 'a' => 'No, para vender en el POS la caja debe estar abierta.' ),
                array( 'q' => '¿Cómo cobro en efectivo?', 'a' => 'En la venta elige efectivo, escribe el monto y registra el cambio si aplica.' ),
                array( 'q' => '¿Cómo cobro por transferencia?', 'a' => 'En la venta elige transferencia y guarda el número de referencia.' ),
                array( 'q' => '¿Puedo mezclar efectivo y transferencia?', 'a' => 'Sí, el POS permite dividir el pago entre ambos métodos.' ),
                array( 'q' => '¿Cómo agrego un cliente a la venta?', 'a' => 'En la venta puedes buscar un cliente existente o crear uno rápido.' ),
                array( 'q' => '¿Puedo aplicar descuentos?', 'a' => 'Sí, el POS permite aplicar un descuento a la venta.' ),
                array( 'q' => '¿Cómo hago una devolución de venta?', 'a' => 'En el historial de ventas elige la venta y anúlala; el stock se repone.' ),
                array( 'q' => '¿Qué pasa con el stock al vender?', 'a' => 'Se descuenta automáticamente del producto vendido.' ),
                array( 'q' => '¿Puedo vender productos fraccionados?', 'a' => 'Sí, el POS maneja fracciones y descuenta del producto madre.' ),
                array( 'q' => '¿Cómo veo mis ventas de hoy?', 'a' => 'En el panel de ventas o pídele al asistente el reporte de ventas de hoy.' ),
                array( 'q' => '¿Puedo vender sin conexión?', 'a' => 'Sí, el POS funciona offline y sincroniza las ventas al reconectar.' ),
                array( 'q' => '¿Cómo asigno la venta a un vendedor?', 'a' => 'Cada vendedor entra con su cuenta y sus ventas quedan asignadas a él.' ),
                array( 'q' => '¿Puedo imprimir un recibo?', 'a' => 'Según tu configuración, puedes imprimir o enviar el recibo de la venta.' ),
                array( 'q' => '¿Qué hago si me equivoco en una venta?', 'a' => 'Anula la venta desde el historial y regístrala de nuevo si es necesario.' ),
                array( 'q' => '¿Puedo cobrar después?', 'a' => 'El POS registra ventas al contado o por transferencia; las cuentas por cobrar se coordinan aparte.' ),
                array( 'q' => '¿Cómo busco un producto en el POS?', 'a' => 'Escribe el nombre o el código del producto en el buscador del POS.' ),
                array( 'q' => '¿Puedo vender productos sin stock?', 'a' => 'El sistema avisa si no hay stock; verifica antes de confirmar.' ),
                array( 'q' => '¿Cómo cierro la jornada de ventas?', 'a' => 'Cierra la caja y haz el arqueo; el sistema calcula el total y las diferencias.' ),
                array( 'q' => '¿Qué es el registro de caja?', 'a' => 'Es el historial de aperturas y cierres de la caja con sus montos.' ),
                array( 'q' => '¿Puedo ver las ventas de otro vendedor?', 'a' => 'El dueño puede ver todas; cada vendedor ve las suyas según permisos.' ),
                array( 'q' => '¿El POS suma el impuesto?', 'a' => 'El precio de venta ya incluye lo que definiste; configura impuestos si tu plan lo permite.' ),
                array( 'q' => '¿Cómo agrego productos rápido?', 'a' => 'Usa el buscador por nombre o código y la venta se arma en segundos.' ),
                array( 'q' => '¿Puedo cancelar una venta ya cerrada?', 'a' => 'Sí, anúlala desde el historial; el stock se repone automáticamente.' ),
                array( 'q' => '¿Qué información guarda la venta?', 'a' => 'Productos, cantidades, total, método de pago, vendedor, cliente y fecha.' ),
                array( 'q' => '¿Puedo vender desde la tableta?', 'a' => 'Sí, el POS funciona en móvil y tableta.' ),
                array( 'q' => '¿Cómo hago una venta a crédito?', 'a' => 'Registra la venta normal y anota la deuda; la cobranza se coordina aparte.' ),
                array( 'q' => '¿Qué pasa si el cliente no paga todo?', 'a' => 'Puedes registrar el monto recibido y la diferencia queda pendiente de cobrar.' ),
                array( 'q' => '¿Dónde veo el total vendido del día?', 'a' => 'En el panel de ventas o pidiendo el reporte al asistente.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Caja y arqueo',
            'items' => array(
                array( 'q' => '¿Cómo abro la caja?', 'a' => 'En el POS pulsa Abrir caja e indica el efectivo inicial.' ),
                array( 'q' => '¿Cómo cierro la caja?', 'a' => 'Pulsa Cerrar caja, escribe el efectivo final y confirma el arqueo.' ),
                array( 'q' => '¿Qué es el arqueo de caja?', 'a' => 'Es el conteo final que compara lo vendido con el efectivo que hay en caja.' ),
                array( 'q' => '¿Qué hago si la caja no cuadra?', 'a' => 'Revisa las ventas del día y los pagos; el arqueo te muestra la diferencia para corregirla.' ),
                array( 'q' => '¿Puedo abrir varias cajas?', 'a' => 'Cada tienda tiene su caja; ábrela por ubicación.' ),
                array( 'q' => '¿Quién puede abrir la caja?', 'a' => 'Depende de los permisos: el dueño y los vendedores autorizados.' ),
                array( 'q' => '¿Se guarda el historial de cajas?', 'a' => 'Sí, cada apertura y cierre queda registrado con sus montos.' ),
                array( 'q' => '¿Puedo reabrir una caja cerrada?', 'a' => 'Cierra el arqueo y abre una nueva caja para continuar vendiendo.' ),
                array( 'q' => '¿Qué pasa si olvido cerrar la caja?', 'a' => 'Puedes cerrarla al día siguiente; el reporte mostrará la jornada completa.' ),
                array( 'q' => '¿El efectivo inicial cuenta en las ventas?', 'a' => 'No, es el fondo con el que empiezas; las ventas se calculan aparte.' ),
                array( 'q' => '¿Cómo veo las diferencias de caja?', 'a' => 'En el reporte del cierre verás lo esperado, lo real y la diferencia.' ),
                array( 'q' => '¿Puedo registrar gastos de caja?', 'a' => 'Algunas configuraciones permiten registrar gastos o retiros de caja.' ),
                array( 'q' => '¿Qué pasa si dos vendedores usan la misma caja?', 'a' => 'Las ventas quedan asignadas a cada vendedor aunque compartan la caja.' ),
                array( 'q' => '¿Puedo ver la caja de otra tienda?', 'a' => 'El dueño puede ver las cajas de sus ubicaciones según permisos.' ),
                array( 'q' => '¿Cómo sé cuánto hay en caja ahora?', 'a' => 'El POS muestra el total en caja de la jornada.' ),
                array( 'q' => '¿Puedo cerrar la caja desde el móvil?', 'a' => 'Sí, el arqueo funciona desde el móvil.' ),
                array( 'q' => '¿Qué pasa si cierro la caja con ventas pendientes?', 'a' => 'Todas las ventas registradas quedan contadas; verifica antes de cerrar.' ),
                array( 'q' => '¿El arqueo incluye transferencias?', 'a' => 'Sí, muestra efectivo, transferencias y el total de la jornada.' ),
                array( 'q' => '¿Puedo editar un arqueo?', 'a' => 'Los arqueos quedan registrados; si hay error, contacta con soporte.' ),
                array( 'q' => '¿Cómo imprimo el cierre de caja?', 'a' => 'El reporte de cierre se puede imprimir o compartir desde el panel.' ),
                array( 'q' => '¿Qué hago si el sistema marca menos efectivo?', 'a' => 'Revisa si hubo gastos o retiros no registrados y ajústalos.' ),
                array( 'q' => '¿Puedo abrir la caja con cero?', 'a' => 'Sí, el efectivo inicial puede ser cero.' ),
                array( 'q' => '¿Qué pasa con las ventas offline al cerrar?', 'a' => 'Al sincronizar, se suman a la caja correspondiente.' ),
                array( 'q' => '¿Cómo asigno la caja a una jornada?', 'a' => 'La caja se asocia al día y la ubicación donde la abriste.' ),
                array( 'q' => '¿Puedo ver cuánto vendió cada vendedor?', 'a' => 'Sí, el reporte de cierre y el de ventas lo muestran por vendedor.' ),
                array( 'q' => '¿Qué pasa si no abro caja y vendo?', 'a' => 'No se puede vender en el POS con la caja cerrada; ábrela primero.' ),
                array( 'q' => '¿La caja se reinicia cada día?', 'a' => 'Cada jornada es independiente; cierras una y abres otra.' ),
                array( 'q' => '¿Puedo tener caja abierta varios días?', 'a' => 'No es recomendable; cierra la jornada para un buen control.' ),
                array( 'q' => '¿Cómo corrijo un pago mal registrado?', 'a' => 'Anula la venta y regístrala de nuevo con el método correcto.' ),
                array( 'q' => '¿Dónde veo el historial de cierres?', 'a' => 'En el módulo de caja o en los reportes de la tienda.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Clientes y CRM',
            'items' => array(
                array( 'q' => '¿Cómo registro un cliente nuevo?', 'a' => 'En el panel de Clientes pulsa Nuevo, completa nombre, teléfono y cualquier nota útil. Si ya existe, el sistema te avisará para evitar duplicados.' ),
                array( 'q' => '¿Cómo veo el historial de compras de un cliente?', 'a' => 'Abre la ficha del cliente desde la lista y revisa ventas, pedidos, productos comprados y total acumulado.' ),
                array( 'q' => '¿Qué es el CRM?', 'a' => 'Es la gestión centralizada de tus clientes: datos, historial, compras, notas internas y seguimiento.' ),
                array( 'q' => '¿Cómo sé quién es mi cliente más valioso?', 'a' => 'Filtra por total gastado, frecuencia de compra y última compra; el CRM te muestra quién más aporta.' ),
                array( 'q' => '¿Puedo editar los datos de un cliente?', 'a' => 'Sí, desde la ficha puedes corregir nombre, teléfono, correo, notas y estado de seguimiento.' ),
                array( 'q' => '¿Cómo hago seguimiento a un cliente?', 'a' => 'Usa notas internas, marca su estado de contacto y revisa su historial para ofrecer promociones o atención personalizada.' ),
                array( 'q' => '¿Puedo crear varios clientes a la vez?', 'a' => 'Sí. Si lo necesitas, puedes pedir al asistente que cree varios clientes de golpe y luego revisarlos en la lista.' ),
                array( 'q' => '¿Qué pasa si el cliente ya existe?', 'a' => 'El sistema busca coincidencias por nombre, teléfono o correo; si ya existe, te evita duplicarlo y enlaza la nueva compra con su historial.' ),
                array( 'q' => '¿Cómo manejo clientes frecuentes?', 'a' => 'El CRM te permite identificarlos por compras repetidas, monto y últimas compras para ofrecerles promociones o atención VIP.' ),
                array( 'q' => '¿Qué es la fidelidad de clientes?', 'a' => 'Es el programa que premia a los clientes que repiten compras con puntos, descuentos o beneficios personalizados.' ),
                array( 'q' => '¿Cómo contacto con un cliente?', 'a' => 'Desde la ficha del cliente tienes su teléfono y correo para hablar por WhatsApp o llamar directamente.' ),
                array( 'q' => '¿Qué información tengo de cada cliente?', 'a' => 'Tienes nombre, teléfono, correo, historial de compras, notas internas y un resumen de su comportamiento.' ),
                array( 'q' => '¿Puedo exportar la lista de clientes?', 'a' => 'Sí, según tu plan puedes exportar la base de clientes para análisis o gestión externa.' ),
                array( 'q' => '¿Cómo filtro clientes por compra o frecuencia?', 'a' => 'Usa el buscador y los filtros de la lista: por gasto total, últimas compras, frecuencia o estado de seguimiento.' ),
                array( 'q' => '¿Qué hago si un cliente repite la misma compra?', 'a' => 'Revisa su historial y ofrecele una compra rápida, un descuento o un recordatorio para reforzar la relación.' ),
                array( 'q' => '¿Cómo anoto una deuda o un pago pendiente?', 'a' => 'Registra la venta y añade la nota o seguimiento correspondiente para no perder el control del cobro.' ),
                array( 'q' => '¿Puedo ver el total que me compra cada cliente?', 'a' => 'Sí. La ficha del cliente muestra compras acumuladas, promedio y tendencia de compra en el tiempo.' ),
                array( 'q' => '¿Cómo busco un cliente por teléfono?', 'a' => 'Escribe el número o parte del nombre en el buscador; el sistema te muestra las coincidencias más relevantes.' ),
                array( 'q' => '¿Cómo agrego un cliente desde el POS?', 'a' => 'En la venta, crea o selecciona al cliente antes de cerrar la compra para que quede vinculado a la operación.' ),
                array( 'q' => '¿Qué pasa si borro un cliente con historial?', 'a' => 'Se recomienda desactivarlo antes de borrarlo para conservar el historial de compras y los datos del negocio.' ),
                array( 'q' => '¿Puedo llevar clientes mayoristas o corporativos?', 'a' => 'Sí, puedes crear clientes con notas y filtros específicos para gestionar mayoristas, pedidos recurrentes o cuentas especiales.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Trabajadores y roles',
            'items' => array(
                array( 'q' => '¿Cómo agrego un trabajador?', 'a' => 'En el panel ve a Trabajadores, invita por correo y asigna el rol.' ),
                array( 'q' => '¿Qué roles existen?', 'a' => 'Dueño, almacenero y vendedor, con permisos diferentes para cada uno.' ),
                array( 'q' => '¿Qué puede hacer un vendedor?', 'a' => 'Vender en el POS, ver pedidos y clientes; no gestiona precios ni elimina productos.' ),
                array( 'q' => '¿Qué puede hacer un almacenero?', 'a' => 'Gestiona el stock: entradas, salidas y transferencias.' ),
                array( 'q' => '¿Qué puede hacer el dueño?', 'a' => 'Todo: productos, precios, stock, equipo, reportes, plan y configuración.' ),
                array( 'q' => '¿Cómo cambio el rol de un trabajador?', 'a' => 'En la lista de trabajadores edita al miembro y cambia su rol.' ),
                array( 'q' => '¿Cómo quito a un trabajador?', 'a' => 'En Trabajadores elimina al miembro; su acceso se revoca al momento.' ),
                array( 'q' => '¿Cuántos trabajadores puedo tener?', 'a' => 'Depende de tu plan; el límite se muestra en el panel > Plan.' ),
                array( 'q' => '¿Un trabajador ve las ventas de todos?', 'a' => 'El vendedor ve sus ventas; el dueño ve todo el negocio.' ),
                array( 'q' => '¿Cómo entra un trabajador?', 'a' => 'Con su correo y contraseña, igual que tú; su rol define lo que ve.' ),
                array( 'q' => '¿Puedo asignar tiendas a un trabajador?', 'a' => 'Sí, puedes asignar al trabajador a ubicaciones específicas.' ),
                array( 'q' => '¿Qué pasa si quito a un trabajador con ventas?', 'a' => 'Sus ventas quedan en el historial; solo se revoca su acceso.' ),
                array( 'q' => '¿Puedo cambiar la contraseña de un trabajador?', 'a' => 'El trabajador puede cambiarla en su perfil; tú puedes restablecerla si hace falta.' ),
                array( 'q' => '¿Cómo veo la actividad de mi equipo?', 'a' => 'Pídele al asistente un reporte del equipo: verás quién ha entrado y cuándo.' ),
                array( 'q' => '¿Qué pasa si un trabajador no entra varios días?', 'a' => 'El reporte del equipo lo marca como inactivo para que lo sepas.' ),
                array( 'q' => '¿Puedo dar permisos especiales?', 'a' => 'Los roles definen los permisos; configura las opciones según tu plan.' ),
                array( 'q' => '¿Un almacenero puede vender?', 'a' => 'Por defecto su rol es de inventario; el dueño puede ajustar permisos si aplica.' ),
                array( 'q' => '¿Cómo se invita a un trabajador?', 'a' => 'En Trabajadores pulsa invitar, escribe su correo y elige el rol; le llega el acceso.' ),
                array( 'q' => '¿El trabajador necesita cuenta en el sitio?', 'a' => 'Sí, entra con su correo; al asignarlo a tu negocio ve solo lo suyo.' ),
                array( 'q' => '¿Qué ve un vendedor en el panel?', 'a' => 'Su punto de venta, pedidos y clientes; no ve reportes de todo el negocio.' ),
                array( 'q' => '¿Puedo tener varios dueños?', 'a' => 'Sí, puedes asignar el rol de dueño a más de una persona.' ),
                array( 'q' => '¿Cómo sé qué rol tengo?', 'a' => 'En tu perfil del panel verás tu rol actual.' ),
                array( 'q' => '¿Qué hago si un trabajador se va?', 'a' => 'Quítalo de Trabajadores para revocar su acceso de inmediato.' ),
                array( 'q' => '¿Puedo ver el historial de un trabajador?', 'a' => 'Sus ventas y movimientos quedan asociados a su cuenta.' ),
                array( 'q' => '¿Los trabajadores ven las cuentas?', 'a' => 'Solo el dueño gestiona plan, facturación y equipo.' ),
                array( 'q' => '¿Puedo cambiar el nombre de un trabajador?', 'a' => 'El trabajador lo cambia en su perfil; tú ves su correo en el equipo.' ),
                array( 'q' => '¿Qué pasa si mi plan baja y tengo muchos trabajadores?', 'a' => 'El sistema te avisa; deberás ajustar el equipo o subir de plan.' ),
                array( 'q' => '¿Puedo pausar el acceso de un trabajador?', 'a' => 'Puedes quitarlo y volverlo a invitar cuando lo necesites.' ),
                array( 'q' => '¿Los permisos se aplican al momento?', 'a' => 'Sí, los cambios de rol o de acceso son inmediatos.' ),
                array( 'q' => '¿Cómo protejo el acceso de mi negocio?', 'a' => 'Revisa el equipo periódicamente y quita a quien ya no trabaje contigo.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Reportes y estadísticas',
            'items' => array(
                array( 'q' => '¿Qué reportes puedo ver?', 'a' => 'Ventas, stock, pedidos, equipo, seguridad y un resumen completo del negocio.' ),
                array( 'q' => '¿Cómo veo las ventas de hoy?', 'a' => 'Pídele al asistente un reporte de ventas o revísalas en el panel de ventas.' ),
                array( 'q' => '¿Cómo veo las ventas del mes?', 'a' => 'Genera un reporte de ventas a 30 días con el asistente.' ),
                array( 'q' => '¿Cómo sé qué producto vende más?', 'a' => 'Pídele al asistente el top de productos más vendidos.' ),
                array( 'q' => '¿Cómo veo el stock bajo?', 'a' => 'El reporte de stock te muestra los productos con poco o sin inventario.' ),
                array( 'q' => '¿Cómo veo los pedidos pendientes?', 'a' => 'El reporte de pedidos te lista los que faltan por atender.' ),
                array( 'q' => '¿Puedo ver la actividad de mi equipo?', 'a' => 'Sí, el reporte del equipo muestra la última actividad de cada trabajador.' ),
                array( 'q' => '¿Puedo programar un reporte?', 'a' => 'Sí, dile al asistente que programe uno para más tarde o cada día.' ),
                array( 'q' => '¿Cómo recibo el reporte programado?', 'a' => 'Te llega como notificación en el chat cuando se genera.' ),
                array( 'q' => '¿Puedo exportar un reporte?', 'a' => 'Según tu plan, puedes exportar o compartir los datos de tus reportes.' ),
                array( 'q' => '¿Los reportes usan datos reales?', 'a' => 'Sí, se generan en vivo con tus ventas, stock y pedidos.' ),
                array( 'q' => '¿Puedo ver las ventas por vendedor?', 'a' => 'Sí, los reportes de ventas se pueden desglosar por vendedor.' ),
                array( 'q' => '¿Cómo veo el total facturado?', 'a' => 'En el reporte de ventas se muestra el total del período elegido.' ),
                array( 'q' => '¿Puedo ver el reporte de seguridad?', 'a' => 'Sí, muestra intentos de acceso fallidos y eventos de seguridad recientes.' ),
                array( 'q' => '¿Qué es el resumen del negocio?', 'a' => 'Es un reporte que junta ventas, stock, pedidos, equipo y seguridad en uno.' ),
                array( 'q' => '¿Puedo ver mis reportes programados?', 'a' => 'Sí, pídele al asistente tus reportes programados.' ),
                array( 'q' => '¿Cómo cancela un reporte programado?', 'a' => 'Por ahora los reportes programados se gestionan desde el asistente; cancélalo escribiendo el tema.' ),
                array( 'q' => '¿Los reportes se guardan?', 'a' => 'El último resultado de cada reporte programado queda disponible en tu lista.' ),
                array( 'q' => '¿Puedo ver el historial de ventas?', 'a' => 'Sí, en el panel de ventas o con el reporte del período que quieras.' ),
                array( 'q' => '¿Qué significa el stock comprometido?', 'a' => 'Es el stock reservado por pedidos pendientes que aún no se descuenta.' ),
                array( 'q' => '¿Puedo ver las ventas por tienda?', 'a' => 'Sí, los reportes se pueden filtrar por ubicación.' ),
                array( 'q' => '¿Cómo veo el rendimiento de un producto?', 'a' => 'El top de ventas te muestra cuánto se vende cada producto.' ),
                array( 'q' => '¿Puedo comparar períodos?', 'a' => 'Genera reportes de distintos períodos y compáralos tú mismo.' ),
                array( 'q' => '¿El reporte diario llega a qué hora?', 'a' => 'El resumen diario automático se programa a las 08:00, y puedes cambiarlo.' ),
                array( 'q' => '¿Puedo pedir un reporte ahora mismo?', 'a' => 'Sí, dile al asistente qué reporte quieres y te lo genera al instante.' ),
                array( 'q' => '¿Qué hago si un reporte no carga?', 'a' => 'Revisa tu conexión e inténtalo de nuevo; si persiste, escríbenos.' ),
                array( 'q' => '¿Los reportes tienen gráficas?', 'a' => 'Por ahora son resúmenes de texto; las gráficas del panel te muestran lo visual.' ),
                array( 'q' => '¿Puedo ver las ventas por método de pago?', 'a' => 'Sí, los datos de efectivo y transferencia están en tus ventas.' ),
                array( 'q' => '¿Cómo sé cuánto debo reponer?', 'a' => 'El reporte de stock bajo te dice exactamente qué falta.' ),
                array( 'q' => '¿Puedo compartir un reporte con mi equipo?', 'a' => 'Puedes copiar el resumen y enviarlo por WhatsApp a quien necesites.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Tu tienda y su apariencia',
            'items' => array(
                array( 'q' => '¿Cómo creo mi tienda?', 'a' => 'Crea tu cuenta, entra al panel y completa los datos de tu tienda: nombre, descripción y ubicación.' ),
                array( 'q' => '¿Cómo cambio el nombre de mi tienda?', 'a' => 'En el panel > Tienda edita el nombre y guarda.' ),
                array( 'q' => '¿Cómo subo el logo?', 'a' => 'En el panel > Tienda sube tu logo desde el dispositivo.' ),
                array( 'q' => '¿Cómo cambio la foto de portada?', 'a' => 'En el panel > Tienda elige la imagen de portada y guarda.' ),
                array( 'q' => '¿Cómo escribo la descripción de mi tienda?', 'a' => 'En el panel > Tienda escribe la descripción que verán los clientes.' ),
                array( 'q' => '¿Cómo pongo mi horario?', 'a' => 'En el panel > Tienda configura el horario de atención.' ),
                array( 'q' => '¿Cómo cambio la dirección?', 'a' => 'En el panel > Tienda actualiza la dirección de tu local.' ),
                array( 'q' => '¿Cómo agrego mi WhatsApp?', 'a' => 'En el panel > Tienda escribe tu número de WhatsApp para recibir pedidos.' ),
                array( 'q' => '¿Cómo agrego otra tienda o ubicación?', 'a' => 'Desde el panel crea una nueva ubicación si tu plan lo permite.' ),
                array( 'q' => '¿Cómo hago visible mi tienda?', 'a' => 'Publica tu tienda con el botón correspondiente y agrega al menos un producto activo.' ),
                array( 'q' => '¿Cómo oculto mi tienda temporalmente?', 'a' => 'Cambia el estado de la tienda a oculta o inactiva.' ),
                array( 'q' => '¿Cómo se ve mi tienda en el marketplace?', 'a' => 'Con tu logo, nombre, descripción y tus productos con precios y stock.' ),
                array( 'q' => '¿Puedo personalizar los colores?', 'a' => 'Según tu plan, puedes ajustar la apariencia y los colores de tu tienda.' ),
                array( 'q' => '¿Cómo actualizo el horario si cambio?', 'a' => 'Vuelve al panel > Tienda y edita el horario cuando necesites.' ),
                array( 'q' => '¿Puedo ver mi tienda como cliente?', 'a' => 'Sí, abre el enlace público de tu tienda desde el panel.' ),
                array( 'q' => '¿Cómo comparto mi tienda?', 'a' => 'Copia el enlace de tu tienda y compártelo por WhatsApp o redes.' ),
                array( 'q' => '¿Cómo agrego una foto a cada producto?', 'a' => 'Al crear o editar el producto sube su imagen.' ),
                array( 'q' => '¿Puedo cambiar el eslogan de mi tienda?', 'a' => 'Sí, en el panel > Tienda puedes añadir un eslogan breve.' ),
                array( 'q' => '¿Qué es la URL de mi tienda?', 'a' => 'Es la dirección web pública donde los clientes ven tu catálogo.' ),
                array( 'q' => '¿Cómo mejoro mi tienda?', 'a' => 'Sube buenas fotos, describe bien los productos y mantén el stock y precios actualizados.' ),
                array( 'q' => '¿Puedo poner mi tienda en pausa?', 'a' => 'Sí, ocúltala temporalmente y actívala cuando quieras volver.' ),
                array( 'q' => '¿Cómo sé si mi tienda está publicada?', 'a' => 'En el panel > Tienda verás su estado actual.' ),
                array( 'q' => '¿Puedo cambiar la moneda de mi tienda?', 'a' => 'Sí, configura la moneda de tus precios en el panel > Tienda.' ),
                array( 'q' => '¿Cómo ordeno mis productos?', 'a' => 'Usa categorías y productos destacados para ordenar el catálogo.' ),
                array( 'q' => '¿Qué hago si mi tienda no aparece?', 'a' => 'Revisa que esté publicada y con productos activos; refresca la página.' ),
                array( 'q' => '¿Puedo tener mi tienda en otra zona?', 'a' => 'Crea una ubicación nueva si tu plan lo permite y asigna sus productos.' ),
                array( 'q' => '¿Cómo actualizo el teléfono de contacto?', 'a' => 'En el panel > Tienda edita el teléfono de tu negocio.' ),
                array( 'q' => '¿Puedo añadir redes sociales?', 'a' => 'Según tu configuración, puedes enlazar tus redes en la tienda.' ),
                array( 'q' => '¿Cómo quito el logo y pongo otro?', 'a' => 'En el panel > Tienda reemplaza la imagen del logo.' ),
                array( 'q' => '¿Los cambios se ven al momento?', 'a' => 'Sí, guarda y tu tienda se actualiza de inmediato.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Notificaciones y alertas',
            'items' => array(
                array( 'q' => '¿Qué notificaciones recibo?', 'a' => 'Pedidos nuevos, stock bajo, actividad del equipo, seguridad y tus reportes programados.' ),
                array( 'q' => '¿Cómo llegan las notificaciones?', 'a' => 'Como avisos en el sitio y en el chat del asistente.' ),
                array( 'q' => '¿Me avisa cuando llega un pedido?', 'a' => 'Sí, el bot se abre con el aviso de pedido nuevo en el panel.' ),
                array( 'q' => '¿Me avisa cuando el stock está bajo?', 'a' => 'Sí, recibes alertas de stock bajo en tus notificaciones.' ),
                array( 'q' => '¿Puedo ver las notificaciones no leídas?', 'a' => 'Sí, el bot muestra el contador de no leídas.' ),
                array( 'q' => '¿Cómo marco una notificación como leída?', 'a' => 'Ábrela y se marca como leída automáticamente.' ),
                array( 'q' => '¿Puedo silenciar las notificaciones?', 'a' => 'Por ahora llegan al panel; si te molestan, escríbenos y lo ajustamos.' ),
                array( 'q' => '¿Me avisa si alguien intenta entrar a mi cuenta?', 'a' => 'Sí, la seguridad te avisa ante intentos de acceso sospechosos.' ),
                array( 'q' => '¿Me avisa si un trabajador no trabaja?', 'a' => 'El reporte diario del equipo marca a quienes llevan días sin actividad.' ),
                array( 'q' => '¿Me avisa cuando vence mi plan?', 'a' => 'Sí, recibes aviso antes de que venza para renovar a tiempo.' ),
                array( 'q' => '¿Qué pasa si tengo muchas notificaciones?', 'a' => 'Se agrupan y puedes ver las recientes desde el panel.' ),
                array( 'q' => '¿Puedo recibir avisos por WhatsApp?', 'a' => 'El contacto directo es por WhatsApp; los avisos del sistema llegan al panel.' ),
                array( 'q' => '¿Cómo veo el historial de notificaciones?', 'a' => 'En el panel de notificaciones verás las recientes.' ),
                array( 'q' => '¿Me avisa si se anula una venta?', 'a' => 'Las ventas y sus anulaciones quedan en el historial y en tus reportes.' ),
                array( 'q' => '¿Me avisa de errores en la web?', 'a' => 'El administrador del sitio recibe aviso de errores graves vía el chat.' ),
                array( 'q' => '¿Puedo ver los avisos del día?', 'a' => 'Sí, tus notificaciones muestran los avisos del día.' ),
                array( 'q' => '¿Los vendedores reciben notificaciones?', 'a' => 'Sí, según su rol ven avisos de sus pedidos y ventas.' ),
                array( 'q' => '¿Cómo desactivo el aviso de stock bajo?', 'a' => 'Configura el stock mínimo o los avisos desde el panel de stock.' ),
                array( 'q' => '¿Me avisa cuando se acepta un pedido?', 'a' => 'El comprador ve el cambio de estado y la tienda coordina por WhatsApp.' ),
                array( 'q' => '¿Puedo recibir el resumen del día?', 'a' => 'Sí, prográmalo con el asistente y te llega cada día.' ),
                array( 'q' => '¿Qué es el badge de no leídas?', 'a' => 'Es el contador rojo que muestra cuántas notificaciones tienes sin ver.' ),
                array( 'q' => '¿Las notificaciones se borran?', 'a' => 'Se conservan las recientes; las antiguas se limpian solas.' ),
                array( 'q' => '¿Me avisa de un carrito abandonado?', 'a' => 'El asistente puede detectar carritos y sugerir retomarlos.' ),
                array( 'q' => '¿Cómo sé si tengo pedidos sin atender?', 'a' => 'La notificación de pedido nuevo te lo recuerda y el reporte de pedidos lo confirma.' ),
                array( 'q' => '¿Me avisa de cambios de plan?', 'a' => 'Sí, recibes confirmación al cambiar de plan.' ),
                array( 'q' => '¿Puedo ver alertas antiguas?', 'a' => 'El panel muestra las notificaciones recientes disponibles.' ),
                array( 'q' => '¿Las alertas llegan aunque esté offline?', 'a' => 'Al reconectar se sincronizan y las ves pendientes.' ),
                array( 'q' => '¿Me avisa si mi tienda se queda sin stock?', 'a' => 'Sí, el aviso de agotados entra en tus notificaciones y reportes.' ),
                array( 'q' => '¿Cómo configuro mis alertas?', 'a' => 'Desde el panel según el módulo: stock mínimo, pedidos, reportes programados.' ),
                array( 'q' => '¿Las notificaciones consumen datos?', 'a' => 'Son ligeras; al estar offline se sincronizan al reconectar.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Modo offline y la app',
            'items' => array(
                array( 'q' => '¿Puedo usar el sitio sin internet?', 'a' => 'Sí, la app guarda lo esencial y sincroniza cuando vuelves a conectarte.' ),
                array( 'q' => '¿Cómo instalo la app en mi teléfono?', 'a' => 'Abre el sitio en el navegador del móvil y elige Añadir a pantalla de inicio.' ),
                array( 'q' => '¿La app ocupa mucho espacio?', 'a' => 'No, es una app web ligera que se instala al momento.' ),
                array( 'q' => '¿Qué puedo hacer offline?', 'a' => 'Ver tu panel, registrar ventas y preparar acciones que se sincronizan después.' ),
                array( 'q' => '¿Qué pasa con las ventas offline?', 'a' => 'Quedan en cola y se envían automáticamente al reconectar.' ),
                array( 'q' => '¿Cómo sé que hay ventas por sincronizar?', 'a' => 'El panel muestra cuántas acciones quedan pendientes de sincronizar.' ),
                array( 'q' => '¿Pierdo datos si cierro la app sin sincronizar?', 'a' => 'No, lo pendiente se guarda en el dispositivo y se envía al reconectar.' ),
                array( 'q' => '¿La app funciona en cualquier teléfono?', 'a' => 'Funciona en los navegadores modernos de Android e iPhone.' ),
                array( 'q' => '¿Necesito descargar algo?', 'a' => 'No, se instala desde el navegador sin pasar por tiendas de aplicaciones.' ),
                array( 'q' => '¿Cómo actualizo la app?', 'a' => 'Se actualiza sola; a veces hay que refrescar la página para tomar los cambios.' ),
                array( 'q' => '¿Qué pasa si la conexión se cae a mitad de una venta?', 'a' => 'La venta queda guardada y se sincroniza cuando vuelva la conexión.' ),
                array( 'q' => '¿Puedo usar el POS sin conexión?', 'a' => 'Sí, el punto de venta funciona offline y sincroniza las ventas después.' ),
                array( 'q' => '¿Cuánto tiempo aguanta el modo offline?', 'a' => 'Los datos guardados permanecen hasta que vuelvas a conectarte.' ),
                array( 'q' => '¿La app consume muchos datos?', 'a' => 'No, está optimizada y el modo offline reduce el consumo.' ),
                array( 'q' => '¿Puedo ver mis reportes offline?', 'a' => 'Lo esencial queda disponible; los datos en vivo se actualizan al conectar.' ),
                array( 'q' => '¿Cómo limpio la memoria de la app?', 'a' => 'Borra los datos del navegador si necesitas; la app se regenera al entrar.' ),
                array( 'q' => '¿La app se puede instalar en una tableta?', 'a' => 'Sí, en tabletas Android e iPad funciona igual.' ),
                array( 'q' => '¿Qué pasa si borro el navegador?', 'a' => 'Se pierde lo guardado local; vuelve a entrar y sincroniza desde el servidor.' ),
                array( 'q' => '¿Puedo tener la app en dos teléfonos?', 'a' => 'Sí, entra con tu cuenta en ambos.' ),
                array( 'q' => '¿Las ventas offline duplican stock?', 'a' => 'No, al sincronizar se aplican una sola vez.' ),
                array( 'q' => '¿Cómo sé la versión de la app?', 'a' => 'La versión se actualiza sola; refresca para asegurar la última.' ),
                array( 'q' => '¿La app funciona en computadora?', 'a' => 'Sí, en el navegador de la computadora funciona igual.' ),
                array( 'q' => '¿Puedo trabajar sin conexión por días?', 'a' => 'Lo guardado permanece; al conectar se sincroniza todo.' ),
                array( 'q' => '¿Qué hago si la sincronización falla?', 'a' => 'Revisa tu conexión y refresca; si persiste, escríbenos y lo revisamos.' ),
                array( 'q' => '¿La app necesita permisos especiales?', 'a' => 'No, funciona desde el navegador sin permisos extra.' ),
                array( 'q' => '¿Puedo desinstalar la app?', 'a' => 'Sí, quita el acceso directo desde el navegador; tus datos quedan en el servidor.' ),
                array( 'q' => '¿Los clientes ven el modo offline?', 'a' => 'El modo offline es para el negocio; los clientes compran online normalmente.' ),
                array( 'q' => '¿Qué hago si la app no responde?', 'a' => 'Refresca la página o cierra y abre la pestaña; casi siempre se resuelve.' ),
                array( 'q' => '¿El chat funciona offline?', 'a' => 'Las preguntas se responden con conexión; lo pendiente se recupera al conectar.' ),
                array( 'q' => '¿Cómo actualizo para ver los últimos cambios?', 'a' => 'Refresca con F5 o cierra y abre la app.' ),
            ),
        ),
        // ------------------------------------------------------------------
        array(
            'topic' => 'Asistente y ayuda',
            'items' => array(
                array( 'q' => '¿Qué es el asistente?', 'a' => 'Es el chat que te ayuda: responde dudas, ejecuta acciones y te genera reportes.' ),
                array( 'q' => '¿Qué puede hacer el asistente?', 'a' => 'Crear productos, reponer stock, aceptar pedidos, registrar ventas, reportes y más.' ),
                array( 'q' => '¿Cómo abro el asistente?', 'a' => 'Toca el botón flotante del chat, abajo a la derecha.' ),
                array( 'q' => '¿El asistente responde de día y de noche?', 'a' => 'Sí, está disponible siempre que tengas conexión.' ),
                array( 'q' => '¿Puedo crear productos desde el chat?', 'a' => 'Sí, dile crear producto y te guía paso a paso, incluso varios a la vez.' ),
                array( 'q' => '¿Puedo reponer stock desde el chat?', 'a' => 'Sí, pide reponer stock, elige producto y cantidad.' ),
                array( 'q' => '¿Puedo aceptar pedidos desde el chat?', 'a' => 'Sí, el asistente te lista los pendientes y los aceptas o rechazas.' ),
                array( 'q' => '¿Puedo registrar ventas desde el chat?', 'a' => 'Sí, con el carrito conversacional: agrega productos y confirma la venta.' ),
                array( 'q' => '¿Puedo pedir reportes al asistente?', 'a' => 'Sí, pide ventas, stock, pedidos, equipo o resumen y te lo genera.' ),
                array( 'q' => '¿Puedo programar reportes?', 'a' => 'Sí, dile que programe un reporte para más tarde o cada día.' ),
                array( 'q' => '¿El asistente conoce las preguntas frecuentes?', 'a' => 'Sí, responde con las FAQs de la página de Ayuda y con el contexto de la app.' ),
                array( 'q' => '¿Qué hago si el asistente no entiende?', 'a' => 'Te sugiere temas y puedes contactar soporte por WhatsApp o Contacto.' ),
                array( 'q' => '¿Puedo hablar con una persona?', 'a' => 'Sí, el asistente te ofrece el WhatsApp y la página de contacto si no resuelve.' ),
                array( 'q' => '¿El asistente usa mis datos reales?', 'a' => 'Sí, cuando tiene conexión usa los datos en vivo de tu negocio.' ),
                array( 'q' => '¿Puedo usar el asistente en el móvil?', 'a' => 'Sí, el chat funciona igual en el móvil.' ),
                array( 'q' => '¿El asistente puede crear clientes?', 'a' => 'Sí, dile crear cliente y te pide nombre y teléfono.' ),
                array( 'q' => '¿Puedo eliminar productos desde el chat?', 'a' => 'Sí, con confirmación para que no borres nada por accidente.' ),
                array( 'q' => '¿Puedo ver mis reportes programados?', 'a' => 'Sí, dile mis reportes y te lista los que tienes.' ),
                array( 'q' => '¿El asistente avisa de pedidos nuevos?', 'a' => 'Sí, se abre con el aviso cuando llega un pedido en el panel.' ),
                array( 'q' => '¿El asistente responde en español?', 'a' => 'Sí, responde en español con tono amable.' ),
                array( 'q' => '¿Puedo pedir una guía de un módulo?', 'a' => 'Sí, escribe guía del panel o pregunta cómo usar un módulo y te explica paso a paso.' ),
                array( 'q' => '¿Qué es el resumen del negocio?', 'a' => 'Un reporte completo de ventas, stock, pedidos, equipo y seguridad.' ),
                array( 'q' => '¿El asistente cobra?', 'a' => 'No, el asistente viene incluido y no tiene costo adicional.' ),
                array( 'q' => '¿Cómo contacto con soporte desde el chat?', 'a' => 'Escribe contacto o ayuda y el asistente te da las vías.' ),
                array( 'q' => '¿El asistente recuerda lo que hablamos?', 'a' => 'Recuerda el contexto de la conversación y tu última acción.' ),
                array( 'q' => '¿Puedo pedir el top de ventas?', 'a' => 'Sí, escribe que te recomiende o qué vende más.' ),
                array( 'q' => '¿Qué hago si el chat no abre?', 'a' => 'Refresca la página y revisa tu conexión; el botón está abajo a la derecha.' ),
                array( 'q' => '¿El asistente puede borrar tareas?', 'a' => 'Los reportes programados se gestionan desde el chat; escribe el tema si necesitas ayuda.' ),
                array( 'q' => '¿Puedo usar el asistente como cliente?', 'a' => 'Sí, te orienta para comprar, seguir pedidos y conocer el sitio.' ),
                array( 'q' => '¿Dónde está la página de Ayuda?', 'a' => 'En el menú del sitio o con el enlace de ayuda; ahí están todas las FAQs.' ),
            ),
        ),
    );
}
